/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.demo;

import com.google.common.base.Preconditions;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;

/**
 * Main plugin class.
 */
public class Plugin extends JavaPlugin {

    private static Plugin instance;

    /**
     * Constructor - Called when plugin is loaded.
     * Ensures that the JavaPluginInit reference is not null.
     * 
     * @param init the plugin initialization object (must not be null)
     * @throws NullPointerException if init is null
     */
    public Plugin(JavaPluginInit init) {
        Preconditions.checkNotNull(init, "JavaPluginInit cannot be null");
        super(init);
        instance = this;
        System.out.println("[Demo Plugin] Plugin loaded!");
    }

    /**
     * Called when plugin is enabled.
     */
    public void onEnable() {
        System.out.println("[Demo Plugin] Plugin enabled!");

        // TODO: Initialize your plugin here
        // - Load configuration
        // - Register event listeners
        // - Register commands
        // - Start services
    }

    /**
     * Called when plugin is disabled.
     */
    public void onDisable() {
        System.out.println("[Demo Plugin] Plugin disabled!");

        // TODO: Cleanup your plugin here
        // - Save data
        // - Stop services
        // - Close connections
    }

    /**
     * Get plugin instance.
     */
    public static Plugin getInstance() {
        return instance;
    }
}
