/*
 * This source file was generated by the Gradle 'init' task
 */
package net.hyvanced;

import com.hypixel.hytale.server.core.event.events.player.PlayerReadyEvent;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.logger.HytaleLogger;
import net.hyvanced.Commands.ItemCommand;
import net.hyvanced.Commands.solarPanelUI;
import net.hyvanced.Events.ExampleEvent;

/**
 * Main plugin class.
 */
public class HyvancedPlugin extends JavaPlugin {

    private static HyvancedPlugin instance;
    private static final HytaleLogger logger = HytaleLogger.forEnclosingClass();

    /**
     * Constructor - Called when plugin is loaded.
     * Ensures that the JavaPluginInit reference is not null.
     *
     * @param init the plugin initialization object (must not be null)
     * @throws NullPointerException if init is null
     */
    public HyvancedPlugin(JavaPluginInit init)
    {
        super(init);
        instance = this;
        logger.atInfo().log("Plugin loaded!");
    }

    @Override
    public void setup()
    {
        logger.atInfo().log("Plugin enabled! test4444");
        this.getCommandRegistry().registerCommand(new ItemCommand());
        this.getEventRegistry().registerGlobal(PlayerReadyEvent.class, ExampleEvent::onPlayerReady);
        this.getCommandRegistry().registerCommand(new solarPanelUI());
    }


    @Override
    public void shutdown() {
        logger.atInfo().log("Plugin disabled!");
    }


    public static HyvancedPlugin getInstance() {
        return instance;
    }
}
