/*
 * This source file was generated by the Gradle 'init' task
 */
package net.example;

import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.logger.HytaleLogger;
import net.example.Commands.ExampleCommand;

/**
 * Main plugin class.
 */
public class ExamplePlugin extends JavaPlugin {

    private static ExamplePlugin instance;
    private static final HytaleLogger logger = HytaleLogger.forEnclosingClass();

    /**
     * Constructor - Called when plugin is loaded.
     * Ensures that the JavaPluginInit reference is not null.
     * 
     * @param init the plugin initialization object (must not be null)
     * @throws NullPointerException if init is null
     */
    public ExamplePlugin(JavaPluginInit init) {
        super(init);
        instance = this;
        logger.atInfo().log("Plugin loaded!");
    }

    /**
     * Called when plugin is enabled.
     */
    @Override
    public void setup() {
        logger.atInfo().log("Plugin enabled! test4444");

        this.getCommandRegistry().registerCommand(new ExampleCommand());

        // TODO: Initialize your plugin here
        // - Load configuration
        // - Register event listeners
        // - Register commands
        // - Start services
    }

    /**
     * Called when plugin is disabled.
     */
    @Override
    public void shutdown() {
        logger.atInfo().log("Plugin disabled!");

        // TODO: Cleanup your plugin here
        // - Save data
        // - Stop services
        // - Close connections
    }

    /**
     * Get plugin instance.
     */
    public static ExamplePlugin getInstance() {
        return instance;
    }
}
